amqp:
  ssl: <%= Rails.application.credentials[Rails.env.to_sym][:amqp][:ssl] %>
  port: <%= Rails.application.credentials[Rails.env.to_sym][:amqp][:port] %>
  host: <%= Rails.application.credentials[Rails.env.to_sym][:amqp][:host] %>
  user: <%= Rails.application.credentials[Rails.env.to_sym][:amqp][:user] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:amqp][:password] %>
  verify_peer: <%= Rails.application.credentials[Rails.env.to_sym][:amqp][:verify_peer] %>
  heartbeat: 10

messages:
  outgoing_queue: fp_to_idb
  incoming_queue: idb_to_fp

:aws:
  :s3_mode: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:s3_mode] %>
  :access_key_id: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:access_key_id] %>
  :secret_access_key: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:secret_access_key] %>
  :region: us-east-2

:storage:
  - :name: draft
    :type: <%= Rails.application.credentials[Rails.env.to_sym][:storage][:draft_type] %>
    :path: <%= Rails.application.credentials[Rails.env.to_sym][:storage][:draft_path] %>
  - :name: medusa
    :type: <%= Rails.application.credentials[Rails.env.to_sym][:storage][:medusa_type] %>
    :path: <%= Rails.application.credentials[Rails.env.to_sym][:storage][:medusa_path] %>
  - :name: tmp
    :type: filesystem
    :path: <%= Rails.application.credentials[Rails.env.to_sym][:storage][:tmp_path] %>
